/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;

import java.awt.*;

/**
 *
 * @author alberto
 */
public class Interface extends javax.swing.JFrame {

    /**
     * Creates new form Interface
     */
    public Interface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Medir = new javax.swing.JButton();
        Texto = new javax.swing.JTextField();
        Bytes = new javax.swing.JLabel();
        CleanerThan = new javax.swing.JLabel();
        Energy = new javax.swing.JLabel();
        GridGrams = new javax.swing.JLabel();
        RenewableGrams = new javax.swing.JLabel();
        Verde = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Medir.setText("jButton1");
        Medir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MedirActionPerformed(evt);
            }
        });
        jPanel1.add(Medir, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 38, -1, -1));

        Texto.setText("jTextField1");
        jPanel1.add(Texto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        Bytes.setText("jLabel2");
        jPanel1.add(Bytes, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, -1, -1));

        CleanerThan.setText("jLabel3");
        jPanel1.add(CleanerThan, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        Energy.setText("jLabel4");
        jPanel1.add(Energy, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, -1, -1));

        GridGrams.setText("jLabel5");
        jPanel1.add(GridGrams, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        RenewableGrams.setText("jLabel6");
        jPanel1.add(RenewableGrams, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, -1, -1));

        Verde.setText("jLabel1");
        jPanel1.add(Verde, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(121, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MedirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MedirActionPerformed

        String text = Texto.getText();
        int bytes = text.getBytes().length;
        Bytes.setText("Bytes: " + bytes);
        CleanerThan.setText("Cleaner than: ");
        Energy.setText("Energy: ");
        GridGrams.setText("Grid grams: ");
        RenewableGrams.setText("Renewable grams: ");
        Verde.setText("Verde: ");





        
    }//GEN-LAST:event_MedirActionPerformed



    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Bytes;
    private javax.swing.JLabel CleanerThan;
    private javax.swing.JLabel Energy;
    private javax.swing.JLabel GridGrams;
    private javax.swing.JButton Medir;
    private javax.swing.JLabel RenewableGrams;
    private javax.swing.JTextField Texto;
    private javax.swing.JLabel Verde;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
